[kube_control_plane]
master1 ansible_host=master1.basile.uha.fr ip=10.129.4.243 etcd_member_name=etcd1 ansible_user=root
master2 ansible_host=master2.basile.uha.fr ip=10.129.4.244 etcd_member_name=etcd2 ansible_user=root
master3 ansible_host=master3.basile.uha.fr ip=10.129.4.245 etcd_member_name=etcd3 ansible_user=root

[etcd:children]
kube_control_plane

[kube_node]
master1
master2
master3
