[kube_control_plane]
master1 ansible_host=master1.basile.local ip=10.30.1.12 etcd_member_name=etcd1 ansible_user=ubuntu
master2 ansible_host=master2.basile.local ip=10.30.1.13 etcd_member_name=etcd2 ansible_user=ubuntu
master3 ansible_host=master3.basile.local ip=10.30.1.14 etcd_member_name=etcd3 ansible_user=ubuntu

[etcd:children]
kube_control_plane

[kube_node]
master1
master2
master3
