[kube_control_plane]
master1 ansible_host=master1.basile.local ip=192.168.2.12 etcd_member_name=etcd1
master2 ansible_host=master2.basile.local ip=192.168.2.13 etcd_member_name=etcd2
master3 ansible_host=master3.basile.local ip=192.168.2.14 etcd_member_name=etcd3

[etcd:children]
kube_control_plane

[kube_node]
master1
master2
master3
